DELETE FROM BEVERAGE;
INSERT INTO BEVERAGE (BEV_NAME, BEV_AMOUNT, BEV_UNIT, BEV_ICON, ACTIVE) VALUES('Beer', 16 , 'oz' ,'beer',1);
INSERT INTO BEVERAGE (BEV_NAME, BEV_AMOUNT, BEV_UNIT, BEV_ICON, ACTIVE) VALUES('Wine', 6 , 'oz' ,'wine',1);