DELETE FROM BEVERAGE;
INSERT INTO BEVERAGE (BEV_NAME, BEV_AMOUNT, BEV_UNIT, BEV_ICON, ACTIVE) VALUES('Water', 8 , 'oz' ,'glass',1);
INSERT INTO BEVERAGE (BEV_NAME, BEV_AMOUNT, BEV_UNIT, BEV_ICON, ACTIVE) VALUES('Water', 16.9 , 'oz' ,'bottle_md',1);
INSERT INTO BEVERAGE (BEV_NAME, BEV_AMOUNT, BEV_UNIT, BEV_ICON, ACTIVE) VALUES('Sports', 20 , 'oz' ,'sports',1);
INSERT INTO BEVERAGE (BEV_NAME, BEV_AMOUNT, BEV_UNIT, BEV_ICON, ACTIVE) VALUES('Beer', 16 , 'oz' ,'beer',1);
INSERT INTO BEVERAGE (BEV_NAME, BEV_AMOUNT, BEV_UNIT, BEV_ICON, ACTIVE) VALUES('Wine', 6 , 'oz' ,'wine',1);